coverage:
  status:
    project:
      default:
        target: auto

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
  require_base: true
  require_head: true
